// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: market_services.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KlineTimeframe int32

const (
	KlineTimeframe_KLINE_TIMEFRAME_UNSPECIFIED KlineTimeframe = 0
	KlineTimeframe_KLINE_TIMEFRAME_1M          KlineTimeframe = 1
)

// Enum value maps for KlineTimeframe.
var (
	KlineTimeframe_name = map[int32]string{
		0: "KLINE_TIMEFRAME_UNSPECIFIED",
		1: "KLINE_TIMEFRAME_1M",
	}
	KlineTimeframe_value = map[string]int32{
		"KLINE_TIMEFRAME_UNSPECIFIED": 0,
		"KLINE_TIMEFRAME_1M":          1,
	}
)

func (x KlineTimeframe) Enum() *KlineTimeframe {
	p := new(KlineTimeframe)
	*p = x
	return p
}

func (x KlineTimeframe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KlineTimeframe) Descriptor() protoreflect.EnumDescriptor {
	return file_market_services_proto_enumTypes[0].Descriptor()
}

func (KlineTimeframe) Type() protoreflect.EnumType {
	return &file_market_services_proto_enumTypes[0]
}

func (x KlineTimeframe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KlineTimeframe.Descriptor instead.
func (KlineTimeframe) EnumDescriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{0}
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_market_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_market_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AssetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	AssetName     string                 `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	AssetSymbol   string                 `protobuf:"bytes,3,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	AssetLogo     string                 `protobuf:"bytes,4,opt,name=asset_logo,json=assetLogo,proto3" json:"asset_logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetItem) Reset() {
	*x = AssetItem{}
	mi := &file_market_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetItem) ProtoMessage() {}

func (x *AssetItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetItem.ProtoReflect.Descriptor instead.
func (*AssetItem) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{2}
}

func (x *AssetItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *AssetItem) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *AssetItem) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *AssetItem) GetAssetLogo() string {
	if x != nil {
		return x.AssetLogo
	}
	return ""
}

type SupportAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportAssetRequest) Reset() {
	*x = SupportAssetRequest{}
	mi := &file_market_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportAssetRequest) ProtoMessage() {}

func (x *SupportAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportAssetRequest.ProtoReflect.Descriptor instead.
func (*SupportAssetRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{3}
}

func (x *SupportAssetRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

type SupportAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Asset         []*AssetItem           `protobuf:"bytes,3,rep,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportAssetResponse) Reset() {
	*x = SupportAssetResponse{}
	mi := &file_market_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportAssetResponse) ProtoMessage() {}

func (x *SupportAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportAssetResponse.ProtoReflect.Descriptor instead.
func (*SupportAssetResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{4}
}

func (x *SupportAssetResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *SupportAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SupportAssetResponse) GetAsset() []*AssetItem {
	if x != nil {
		return x.Asset
	}
	return nil
}

type MarketSymbolItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Guid           string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	SymbolName     string                 `protobuf:"bytes,2,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	BaseAssetGuid  string                 `protobuf:"bytes,3,opt,name=base_asset_guid,json=baseAssetGuid,proto3" json:"base_asset_guid,omitempty"`
	QuoteAssetGuid string                 `protobuf:"bytes,4,opt,name=quote_asset_guid,json=quoteAssetGuid,proto3" json:"quote_asset_guid,omitempty"`
	MarketType     string                 `protobuf:"bytes,5,opt,name=market_type,json=marketType,proto3" json:"market_type,omitempty"`
	IsActive       bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarketSymbolItem) Reset() {
	*x = MarketSymbolItem{}
	mi := &file_market_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketSymbolItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketSymbolItem) ProtoMessage() {}

func (x *MarketSymbolItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketSymbolItem.ProtoReflect.Descriptor instead.
func (*MarketSymbolItem) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{5}
}

func (x *MarketSymbolItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *MarketSymbolItem) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

func (x *MarketSymbolItem) GetBaseAssetGuid() string {
	if x != nil {
		return x.BaseAssetGuid
	}
	return ""
}

func (x *MarketSymbolItem) GetQuoteAssetGuid() string {
	if x != nil {
		return x.QuoteAssetGuid
	}
	return ""
}

func (x *MarketSymbolItem) GetMarketType() string {
	if x != nil {
		return x.MarketType
	}
	return ""
}

func (x *MarketSymbolItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *MarketSymbolItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MarketSymbolItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListMarketSymbolsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pagination     *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OnlyActive     bool                   `protobuf:"varint,2,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	BaseAssetGuid  string                 `protobuf:"bytes,3,opt,name=base_asset_guid,json=baseAssetGuid,proto3" json:"base_asset_guid,omitempty"`
	QuoteAssetGuid string                 `protobuf:"bytes,4,opt,name=quote_asset_guid,json=quoteAssetGuid,proto3" json:"quote_asset_guid,omitempty"`
	MarketType     string                 `protobuf:"bytes,5,opt,name=market_type,json=marketType,proto3" json:"market_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMarketSymbolsRequest) Reset() {
	*x = ListMarketSymbolsRequest{}
	mi := &file_market_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketSymbolsRequest) ProtoMessage() {}

func (x *ListMarketSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketSymbolsRequest.ProtoReflect.Descriptor instead.
func (*ListMarketSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{6}
}

func (x *ListMarketSymbolsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMarketSymbolsRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *ListMarketSymbolsRequest) GetBaseAssetGuid() string {
	if x != nil {
		return x.BaseAssetGuid
	}
	return ""
}

func (x *ListMarketSymbolsRequest) GetQuoteAssetGuid() string {
	if x != nil {
		return x.QuoteAssetGuid
	}
	return ""
}

func (x *ListMarketSymbolsRequest) GetMarketType() string {
	if x != nil {
		return x.MarketType
	}
	return ""
}

type ListMarketSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Result        []*MarketSymbolItem    `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketSymbolsResponse) Reset() {
	*x = ListMarketSymbolsResponse{}
	mi := &file_market_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketSymbolsResponse) ProtoMessage() {}

func (x *ListMarketSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketSymbolsResponse.ProtoReflect.Descriptor instead.
func (*ListMarketSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{7}
}

func (x *ListMarketSymbolsResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *ListMarketSymbolsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListMarketSymbolsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMarketSymbolsResponse) GetResult() []*MarketSymbolItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type SymbolMarketItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	SymbolGuid    string                 `protobuf:"bytes,2,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	AskPrice      string                 `protobuf:"bytes,4,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	BidPrice      string                 `protobuf:"bytes,5,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	Volume        string                 `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	MarketCap     string                 `protobuf:"bytes,7,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	Radio         string                 `protobuf:"bytes,8,opt,name=radio,proto3" json:"radio,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolMarketItem) Reset() {
	*x = SymbolMarketItem{}
	mi := &file_market_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolMarketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolMarketItem) ProtoMessage() {}

func (x *SymbolMarketItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolMarketItem.ProtoReflect.Descriptor instead.
func (*SymbolMarketItem) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{8}
}

func (x *SymbolMarketItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *SymbolMarketItem) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

func (x *SymbolMarketItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SymbolMarketItem) GetAskPrice() string {
	if x != nil {
		return x.AskPrice
	}
	return ""
}

func (x *SymbolMarketItem) GetBidPrice() string {
	if x != nil {
		return x.BidPrice
	}
	return ""
}

func (x *SymbolMarketItem) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *SymbolMarketItem) GetMarketCap() string {
	if x != nil {
		return x.MarketCap
	}
	return ""
}

func (x *SymbolMarketItem) GetRadio() string {
	if x != nil {
		return x.Radio
	}
	return ""
}

func (x *SymbolMarketItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SymbolMarketItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SymbolMarketItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListSymbolMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,2,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	SymbolGuid    string                 `protobuf:"bytes,3,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolMarketsRequest) Reset() {
	*x = ListSymbolMarketsRequest{}
	mi := &file_market_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolMarketsRequest) ProtoMessage() {}

func (x *ListSymbolMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolMarketsRequest.ProtoReflect.Descriptor instead.
func (*ListSymbolMarketsRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{9}
}

func (x *ListSymbolMarketsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListSymbolMarketsRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *ListSymbolMarketsRequest) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

type ListSymbolMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Result        []*SymbolMarketItem    `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolMarketsResponse) Reset() {
	*x = ListSymbolMarketsResponse{}
	mi := &file_market_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolMarketsResponse) ProtoMessage() {}

func (x *ListSymbolMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolMarketsResponse.ProtoReflect.Descriptor instead.
func (*ListSymbolMarketsResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{10}
}

func (x *ListSymbolMarketsResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *ListSymbolMarketsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListSymbolMarketsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListSymbolMarketsResponse) GetResult() []*SymbolMarketItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetSymbolMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolGuid    string                 `protobuf:"bytes,1,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolMarketRequest) Reset() {
	*x = GetSymbolMarketRequest{}
	mi := &file_market_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolMarketRequest) ProtoMessage() {}

func (x *GetSymbolMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolMarketRequest.ProtoReflect.Descriptor instead.
func (*GetSymbolMarketRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{11}
}

func (x *GetSymbolMarketRequest) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

type GetSymbolMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *SymbolMarketItem      `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolMarketResponse) Reset() {
	*x = GetSymbolMarketResponse{}
	mi := &file_market_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolMarketResponse) ProtoMessage() {}

func (x *GetSymbolMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolMarketResponse.ProtoReflect.Descriptor instead.
func (*GetSymbolMarketResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{12}
}

func (x *GetSymbolMarketResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *GetSymbolMarketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSymbolMarketResponse) GetResult() *SymbolMarketItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type CurrencyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	CurrencyName  string                 `protobuf:"bytes,2,opt,name=currency_name,json=currencyName,proto3" json:"currency_name,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Rate          string                 `protobuf:"bytes,4,opt,name=rate,proto3" json:"rate,omitempty"`
	BuySpread     string                 `protobuf:"bytes,5,opt,name=buy_spread,json=buySpread,proto3" json:"buy_spread,omitempty"`
	SellSpread    string                 `protobuf:"bytes,6,opt,name=sell_spread,json=sellSpread,proto3" json:"sell_spread,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyItem) Reset() {
	*x = CurrencyItem{}
	mi := &file_market_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyItem) ProtoMessage() {}

func (x *CurrencyItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyItem.ProtoReflect.Descriptor instead.
func (*CurrencyItem) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{13}
}

func (x *CurrencyItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *CurrencyItem) GetCurrencyName() string {
	if x != nil {
		return x.CurrencyName
	}
	return ""
}

func (x *CurrencyItem) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CurrencyItem) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *CurrencyItem) GetBuySpread() string {
	if x != nil {
		return x.BuySpread
	}
	return ""
}

func (x *CurrencyItem) GetSellSpread() string {
	if x != nil {
		return x.SellSpread
	}
	return ""
}

func (x *CurrencyItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CurrencyItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CurrencyItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,2,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesRequest) Reset() {
	*x = ListCurrenciesRequest{}
	mi := &file_market_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesRequest) ProtoMessage() {}

func (x *ListCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*ListCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{14}
}

func (x *ListCurrenciesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCurrenciesRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *ListCurrenciesRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type ListCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Result        []*CurrencyItem        `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesResponse) Reset() {
	*x = ListCurrenciesResponse{}
	mi := &file_market_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesResponse) ProtoMessage() {}

func (x *ListCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{15}
}

func (x *ListCurrenciesResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *ListCurrenciesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListCurrenciesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCurrenciesResponse) GetResult() []*CurrencyItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type SymbolMarketCurrencyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	SymbolGuid    string                 `protobuf:"bytes,2,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	CurrencyGuid  string                 `protobuf:"bytes,3,opt,name=currency_guid,json=currencyGuid,proto3" json:"currency_guid,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	AskPrice      string                 `protobuf:"bytes,5,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	BidPrice      string                 `protobuf:"bytes,6,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolMarketCurrencyItem) Reset() {
	*x = SymbolMarketCurrencyItem{}
	mi := &file_market_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolMarketCurrencyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolMarketCurrencyItem) ProtoMessage() {}

func (x *SymbolMarketCurrencyItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolMarketCurrencyItem.ProtoReflect.Descriptor instead.
func (*SymbolMarketCurrencyItem) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{16}
}

func (x *SymbolMarketCurrencyItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *SymbolMarketCurrencyItem) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

func (x *SymbolMarketCurrencyItem) GetCurrencyGuid() string {
	if x != nil {
		return x.CurrencyGuid
	}
	return ""
}

func (x *SymbolMarketCurrencyItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SymbolMarketCurrencyItem) GetAskPrice() string {
	if x != nil {
		return x.AskPrice
	}
	return ""
}

func (x *SymbolMarketCurrencyItem) GetBidPrice() string {
	if x != nil {
		return x.BidPrice
	}
	return ""
}

func (x *SymbolMarketCurrencyItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SymbolMarketCurrencyItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SymbolMarketCurrencyItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListSymbolMarketCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,2,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	SymbolGuid    string                 `protobuf:"bytes,3,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	CurrencyGuid  string                 `protobuf:"bytes,4,opt,name=currency_guid,json=currencyGuid,proto3" json:"currency_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolMarketCurrenciesRequest) Reset() {
	*x = ListSymbolMarketCurrenciesRequest{}
	mi := &file_market_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolMarketCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolMarketCurrenciesRequest) ProtoMessage() {}

func (x *ListSymbolMarketCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolMarketCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*ListSymbolMarketCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{17}
}

func (x *ListSymbolMarketCurrenciesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListSymbolMarketCurrenciesRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *ListSymbolMarketCurrenciesRequest) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

func (x *ListSymbolMarketCurrenciesRequest) GetCurrencyGuid() string {
	if x != nil {
		return x.CurrencyGuid
	}
	return ""
}

type ListSymbolMarketCurrenciesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ReturnCode    uint64                      `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Pagination    *PaginationResponse         `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Result        []*SymbolMarketCurrencyItem `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolMarketCurrenciesResponse) Reset() {
	*x = ListSymbolMarketCurrenciesResponse{}
	mi := &file_market_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolMarketCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolMarketCurrenciesResponse) ProtoMessage() {}

func (x *ListSymbolMarketCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolMarketCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListSymbolMarketCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{18}
}

func (x *ListSymbolMarketCurrenciesResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *ListSymbolMarketCurrenciesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListSymbolMarketCurrenciesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListSymbolMarketCurrenciesResponse) GetResult() []*SymbolMarketCurrencyItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetSymbolMarketCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolGuid    string                 `protobuf:"bytes,1,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	CurrencyGuid  string                 `protobuf:"bytes,2,opt,name=currency_guid,json=currencyGuid,proto3" json:"currency_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolMarketCurrencyRequest) Reset() {
	*x = GetSymbolMarketCurrencyRequest{}
	mi := &file_market_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolMarketCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolMarketCurrencyRequest) ProtoMessage() {}

func (x *GetSymbolMarketCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolMarketCurrencyRequest.ProtoReflect.Descriptor instead.
func (*GetSymbolMarketCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{19}
}

func (x *GetSymbolMarketCurrencyRequest) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

func (x *GetSymbolMarketCurrencyRequest) GetCurrencyGuid() string {
	if x != nil {
		return x.CurrencyGuid
	}
	return ""
}

type GetSymbolMarketCurrencyResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ReturnCode    uint64                    `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *SymbolMarketCurrencyItem `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolMarketCurrencyResponse) Reset() {
	*x = GetSymbolMarketCurrencyResponse{}
	mi := &file_market_services_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolMarketCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolMarketCurrencyResponse) ProtoMessage() {}

func (x *GetSymbolMarketCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolMarketCurrencyResponse.ProtoReflect.Descriptor instead.
func (*GetSymbolMarketCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{20}
}

func (x *GetSymbolMarketCurrencyResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *GetSymbolMarketCurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSymbolMarketCurrencyResponse) GetResult() *SymbolMarketCurrencyItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type SymbolKlineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	SymbolGuid    string                 `protobuf:"bytes,2,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	Timeframe     KlineTimeframe         `protobuf:"varint,3,opt,name=timeframe,proto3,enum=xyz.MarketServer.KlineTimeframe" json:"timeframe,omitempty"`
	OpenPrice     string                 `protobuf:"bytes,4,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	ClosePrice    string                 `protobuf:"bytes,5,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	HighPrice     string                 `protobuf:"bytes,6,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	LowPrice      string                 `protobuf:"bytes,7,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	Volume        string                 `protobuf:"bytes,8,opt,name=volume,proto3" json:"volume,omitempty"`
	MarketCap     string                 `protobuf:"bytes,9,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolKlineItem) Reset() {
	*x = SymbolKlineItem{}
	mi := &file_market_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolKlineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolKlineItem) ProtoMessage() {}

func (x *SymbolKlineItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolKlineItem.ProtoReflect.Descriptor instead.
func (*SymbolKlineItem) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{21}
}

func (x *SymbolKlineItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *SymbolKlineItem) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

func (x *SymbolKlineItem) GetTimeframe() KlineTimeframe {
	if x != nil {
		return x.Timeframe
	}
	return KlineTimeframe_KLINE_TIMEFRAME_UNSPECIFIED
}

func (x *SymbolKlineItem) GetOpenPrice() string {
	if x != nil {
		return x.OpenPrice
	}
	return ""
}

func (x *SymbolKlineItem) GetClosePrice() string {
	if x != nil {
		return x.ClosePrice
	}
	return ""
}

func (x *SymbolKlineItem) GetHighPrice() string {
	if x != nil {
		return x.HighPrice
	}
	return ""
}

func (x *SymbolKlineItem) GetLowPrice() string {
	if x != nil {
		return x.LowPrice
	}
	return ""
}

func (x *SymbolKlineItem) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *SymbolKlineItem) GetMarketCap() string {
	if x != nil {
		return x.MarketCap
	}
	return ""
}

func (x *SymbolKlineItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SymbolKlineItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SymbolKlineItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListKlinesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SymbolGuid     string                 `protobuf:"bytes,1,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	Timeframe      KlineTimeframe         `protobuf:"varint,2,opt,name=timeframe,proto3,enum=xyz.MarketServer.KlineTimeframe" json:"timeframe,omitempty"`
	StartTimestamp int64                  `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   int64                  `protobuf:"varint,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Pagination     *PaginationRequest     `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OnlyActive     bool                   `protobuf:"varint,6,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListKlinesRequest) Reset() {
	*x = ListKlinesRequest{}
	mi := &file_market_services_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKlinesRequest) ProtoMessage() {}

func (x *ListKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKlinesRequest.ProtoReflect.Descriptor instead.
func (*ListKlinesRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{22}
}

func (x *ListKlinesRequest) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

func (x *ListKlinesRequest) GetTimeframe() KlineTimeframe {
	if x != nil {
		return x.Timeframe
	}
	return KlineTimeframe_KLINE_TIMEFRAME_UNSPECIFIED
}

func (x *ListKlinesRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *ListKlinesRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *ListKlinesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListKlinesRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

type ListKlinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Result        []*SymbolKlineItem     `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKlinesResponse) Reset() {
	*x = ListKlinesResponse{}
	mi := &file_market_services_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKlinesResponse) ProtoMessage() {}

func (x *ListKlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKlinesResponse.ProtoReflect.Descriptor instead.
func (*ListKlinesResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{23}
}

func (x *ListKlinesResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *ListKlinesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListKlinesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListKlinesResponse) GetResult() []*SymbolKlineItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type ExchangeSymbolKlineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	ExchangeGuid  string                 `protobuf:"bytes,2,opt,name=exchange_guid,json=exchangeGuid,proto3" json:"exchange_guid,omitempty"`
	SymbolGuid    string                 `protobuf:"bytes,3,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	Timeframe     KlineTimeframe         `protobuf:"varint,4,opt,name=timeframe,proto3,enum=xyz.MarketServer.KlineTimeframe" json:"timeframe,omitempty"`
	OpenPrice     string                 `protobuf:"bytes,5,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	ClosePrice    string                 `protobuf:"bytes,6,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	HighPrice     string                 `protobuf:"bytes,7,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	LowPrice      string                 `protobuf:"bytes,8,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	Volume        string                 `protobuf:"bytes,9,opt,name=volume,proto3" json:"volume,omitempty"`
	MarketCap     string                 `protobuf:"bytes,10,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	IsActive      bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeSymbolKlineItem) Reset() {
	*x = ExchangeSymbolKlineItem{}
	mi := &file_market_services_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeSymbolKlineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeSymbolKlineItem) ProtoMessage() {}

func (x *ExchangeSymbolKlineItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeSymbolKlineItem.ProtoReflect.Descriptor instead.
func (*ExchangeSymbolKlineItem) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{24}
}

func (x *ExchangeSymbolKlineItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetExchangeGuid() string {
	if x != nil {
		return x.ExchangeGuid
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetTimeframe() KlineTimeframe {
	if x != nil {
		return x.Timeframe
	}
	return KlineTimeframe_KLINE_TIMEFRAME_UNSPECIFIED
}

func (x *ExchangeSymbolKlineItem) GetOpenPrice() string {
	if x != nil {
		return x.OpenPrice
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetClosePrice() string {
	if x != nil {
		return x.ClosePrice
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetHighPrice() string {
	if x != nil {
		return x.HighPrice
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetLowPrice() string {
	if x != nil {
		return x.LowPrice
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetMarketCap() string {
	if x != nil {
		return x.MarketCap
	}
	return ""
}

func (x *ExchangeSymbolKlineItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ExchangeSymbolKlineItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ExchangeSymbolKlineItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListExchangeKlinesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SymbolGuid     string                 `protobuf:"bytes,1,opt,name=symbol_guid,json=symbolGuid,proto3" json:"symbol_guid,omitempty"`
	ExchangeGuid   string                 `protobuf:"bytes,2,opt,name=exchange_guid,json=exchangeGuid,proto3" json:"exchange_guid,omitempty"`
	Timeframe      KlineTimeframe         `protobuf:"varint,3,opt,name=timeframe,proto3,enum=xyz.MarketServer.KlineTimeframe" json:"timeframe,omitempty"`
	StartTimestamp int64                  `protobuf:"varint,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   int64                  `protobuf:"varint,5,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Pagination     *PaginationRequest     `protobuf:"bytes,6,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OnlyActive     bool                   `protobuf:"varint,7,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListExchangeKlinesRequest) Reset() {
	*x = ListExchangeKlinesRequest{}
	mi := &file_market_services_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExchangeKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExchangeKlinesRequest) ProtoMessage() {}

func (x *ListExchangeKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExchangeKlinesRequest.ProtoReflect.Descriptor instead.
func (*ListExchangeKlinesRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{25}
}

func (x *ListExchangeKlinesRequest) GetSymbolGuid() string {
	if x != nil {
		return x.SymbolGuid
	}
	return ""
}

func (x *ListExchangeKlinesRequest) GetExchangeGuid() string {
	if x != nil {
		return x.ExchangeGuid
	}
	return ""
}

func (x *ListExchangeKlinesRequest) GetTimeframe() KlineTimeframe {
	if x != nil {
		return x.Timeframe
	}
	return KlineTimeframe_KLINE_TIMEFRAME_UNSPECIFIED
}

func (x *ListExchangeKlinesRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *ListExchangeKlinesRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *ListExchangeKlinesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListExchangeKlinesRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

type ListExchangeKlinesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ReturnCode    uint64                     `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Pagination    *PaginationResponse        `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Result        []*ExchangeSymbolKlineItem `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExchangeKlinesResponse) Reset() {
	*x = ListExchangeKlinesResponse{}
	mi := &file_market_services_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExchangeKlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExchangeKlinesResponse) ProtoMessage() {}

func (x *ListExchangeKlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExchangeKlinesResponse.ProtoReflect.Descriptor instead.
func (*ListExchangeKlinesResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{26}
}

func (x *ListExchangeKlinesResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *ListExchangeKlinesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListExchangeKlinesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListExchangeKlinesResponse) GetResult() []*ExchangeSymbolKlineItem {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_market_services_proto protoreflect.FileDescriptor

const file_market_services_proto_rawDesc = "" +
	"\n" +
	"\x15market_services.proto\x12\x10xyz.MarketServer\"D\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"[\n" +
	"\x12PaginationResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\x80\x01\n" +
	"\tAssetItem\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12!\n" +
	"\fasset_symbol\x18\x03 \x01(\tR\vassetSymbol\x12\x1d\n" +
	"\n" +
	"asset_logo\x18\x04 \x01(\tR\tassetLogo\"<\n" +
	"\x13SupportAssetRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\"\x84\x01\n" +
	"\x14SupportAssetResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x05asset\x18\x03 \x03(\v2\x1b.xyz.MarketServer.AssetItemR\x05asset\"\x95\x02\n" +
	"\x10MarketSymbolItem\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1f\n" +
	"\vsymbol_name\x18\x02 \x01(\tR\n" +
	"symbolName\x12&\n" +
	"\x0fbase_asset_guid\x18\x03 \x01(\tR\rbaseAssetGuid\x12(\n" +
	"\x10quote_asset_guid\x18\x04 \x01(\tR\x0equoteAssetGuid\x12\x1f\n" +
	"\vmarket_type\x18\x05 \x01(\tR\n" +
	"marketType\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xf3\x01\n" +
	"\x18ListMarketSymbolsRequest\x12C\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.xyz.MarketServer.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vonly_active\x18\x02 \x01(\bR\n" +
	"onlyActive\x12&\n" +
	"\x0fbase_asset_guid\x18\x03 \x01(\tR\rbaseAssetGuid\x12(\n" +
	"\x10quote_asset_guid\x18\x04 \x01(\tR\x0equoteAssetGuid\x12\x1f\n" +
	"\vmarket_type\x18\x05 \x01(\tR\n" +
	"marketType\"\xd8\x01\n" +
	"\x19ListMarketSymbolsResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.xyz.MarketServer.PaginationResponseR\n" +
	"pagination\x12:\n" +
	"\x06result\x18\x04 \x03(\v2\".xyz.MarketServer.MarketSymbolItemR\x06result\"\xbf\x02\n" +
	"\x10SymbolMarketItem\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1f\n" +
	"\vsymbol_guid\x18\x02 \x01(\tR\n" +
	"symbolGuid\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x1b\n" +
	"\task_price\x18\x04 \x01(\tR\baskPrice\x12\x1b\n" +
	"\tbid_price\x18\x05 \x01(\tR\bbidPrice\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\tR\x06volume\x12\x1d\n" +
	"\n" +
	"market_cap\x18\a \x01(\tR\tmarketCap\x12\x14\n" +
	"\x05radio\x18\b \x01(\tR\x05radio\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xa1\x01\n" +
	"\x18ListSymbolMarketsRequest\x12C\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.xyz.MarketServer.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vonly_active\x18\x02 \x01(\bR\n" +
	"onlyActive\x12\x1f\n" +
	"\vsymbol_guid\x18\x03 \x01(\tR\n" +
	"symbolGuid\"\xd8\x01\n" +
	"\x19ListSymbolMarketsResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.xyz.MarketServer.PaginationResponseR\n" +
	"pagination\x12:\n" +
	"\x06result\x18\x04 \x03(\v2\".xyz.MarketServer.SymbolMarketItemR\x06result\"9\n" +
	"\x16GetSymbolMarketRequest\x12\x1f\n" +
	"\vsymbol_guid\x18\x01 \x01(\tR\n" +
	"symbolGuid\"\x90\x01\n" +
	"\x17GetSymbolMarketResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x06result\x18\x03 \x01(\v2\".xyz.MarketServer.SymbolMarketItemR\x06result\"\x9b\x02\n" +
	"\fCurrencyItem\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12#\n" +
	"\rcurrency_name\x18\x02 \x01(\tR\fcurrencyName\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\tR\x04rate\x12\x1d\n" +
	"\n" +
	"buy_spread\x18\x05 \x01(\tR\tbuySpread\x12\x1f\n" +
	"\vsell_spread\x18\x06 \x01(\tR\n" +
	"sellSpread\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\xa2\x01\n" +
	"\x15ListCurrenciesRequest\x12C\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.xyz.MarketServer.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vonly_active\x18\x02 \x01(\bR\n" +
	"onlyActive\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\"\xd1\x01\n" +
	"\x16ListCurrenciesResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.xyz.MarketServer.PaginationResponseR\n" +
	"pagination\x126\n" +
	"\x06result\x18\x04 \x03(\v2\x1e.xyz.MarketServer.CurrencyItemR\x06result\"\x9f\x02\n" +
	"\x18SymbolMarketCurrencyItem\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1f\n" +
	"\vsymbol_guid\x18\x02 \x01(\tR\n" +
	"symbolGuid\x12#\n" +
	"\rcurrency_guid\x18\x03 \x01(\tR\fcurrencyGuid\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x1b\n" +
	"\task_price\x18\x05 \x01(\tR\baskPrice\x12\x1b\n" +
	"\tbid_price\x18\x06 \x01(\tR\bbidPrice\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\xcf\x01\n" +
	"!ListSymbolMarketCurrenciesRequest\x12C\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.xyz.MarketServer.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vonly_active\x18\x02 \x01(\bR\n" +
	"onlyActive\x12\x1f\n" +
	"\vsymbol_guid\x18\x03 \x01(\tR\n" +
	"symbolGuid\x12#\n" +
	"\rcurrency_guid\x18\x04 \x01(\tR\fcurrencyGuid\"\xe9\x01\n" +
	"\"ListSymbolMarketCurrenciesResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.xyz.MarketServer.PaginationResponseR\n" +
	"pagination\x12B\n" +
	"\x06result\x18\x04 \x03(\v2*.xyz.MarketServer.SymbolMarketCurrencyItemR\x06result\"f\n" +
	"\x1eGetSymbolMarketCurrencyRequest\x12\x1f\n" +
	"\vsymbol_guid\x18\x01 \x01(\tR\n" +
	"symbolGuid\x12#\n" +
	"\rcurrency_guid\x18\x02 \x01(\tR\fcurrencyGuid\"\xa0\x01\n" +
	"\x1fGetSymbolMarketCurrencyResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x06result\x18\x03 \x01(\v2*.xyz.MarketServer.SymbolMarketCurrencyItemR\x06result\"\x94\x03\n" +
	"\x0fSymbolKlineItem\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1f\n" +
	"\vsymbol_guid\x18\x02 \x01(\tR\n" +
	"symbolGuid\x12>\n" +
	"\ttimeframe\x18\x03 \x01(\x0e2 .xyz.MarketServer.KlineTimeframeR\ttimeframe\x12\x1d\n" +
	"\n" +
	"open_price\x18\x04 \x01(\tR\topenPrice\x12\x1f\n" +
	"\vclose_price\x18\x05 \x01(\tR\n" +
	"closePrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\x06 \x01(\tR\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\a \x01(\tR\blowPrice\x12\x16\n" +
	"\x06volume\x18\b \x01(\tR\x06volume\x12\x1d\n" +
	"\n" +
	"market_cap\x18\t \x01(\tR\tmarketCap\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"\xa8\x02\n" +
	"\x11ListKlinesRequest\x12\x1f\n" +
	"\vsymbol_guid\x18\x01 \x01(\tR\n" +
	"symbolGuid\x12>\n" +
	"\ttimeframe\x18\x02 \x01(\x0e2 .xyz.MarketServer.KlineTimeframeR\ttimeframe\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x04 \x01(\x03R\fendTimestamp\x12C\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2#.xyz.MarketServer.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vonly_active\x18\x06 \x01(\bR\n" +
	"onlyActive\"\xd0\x01\n" +
	"\x12ListKlinesResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.xyz.MarketServer.PaginationResponseR\n" +
	"pagination\x129\n" +
	"\x06result\x18\x04 \x03(\v2!.xyz.MarketServer.SymbolKlineItemR\x06result\"\xc1\x03\n" +
	"\x17ExchangeSymbolKlineItem\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12#\n" +
	"\rexchange_guid\x18\x02 \x01(\tR\fexchangeGuid\x12\x1f\n" +
	"\vsymbol_guid\x18\x03 \x01(\tR\n" +
	"symbolGuid\x12>\n" +
	"\ttimeframe\x18\x04 \x01(\x0e2 .xyz.MarketServer.KlineTimeframeR\ttimeframe\x12\x1d\n" +
	"\n" +
	"open_price\x18\x05 \x01(\tR\topenPrice\x12\x1f\n" +
	"\vclose_price\x18\x06 \x01(\tR\n" +
	"closePrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\a \x01(\tR\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\b \x01(\tR\blowPrice\x12\x16\n" +
	"\x06volume\x18\t \x01(\tR\x06volume\x12\x1d\n" +
	"\n" +
	"market_cap\x18\n" +
	" \x01(\tR\tmarketCap\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\"\xd5\x02\n" +
	"\x19ListExchangeKlinesRequest\x12\x1f\n" +
	"\vsymbol_guid\x18\x01 \x01(\tR\n" +
	"symbolGuid\x12#\n" +
	"\rexchange_guid\x18\x02 \x01(\tR\fexchangeGuid\x12>\n" +
	"\ttimeframe\x18\x03 \x01(\x0e2 .xyz.MarketServer.KlineTimeframeR\ttimeframe\x12'\n" +
	"\x0fstart_timestamp\x18\x04 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x05 \x01(\x03R\fendTimestamp\x12C\n" +
	"\n" +
	"pagination\x18\x06 \x01(\v2#.xyz.MarketServer.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vonly_active\x18\a \x01(\bR\n" +
	"onlyActive\"\xe0\x01\n" +
	"\x1aListExchangeKlinesResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.xyz.MarketServer.PaginationResponseR\n" +
	"pagination\x12A\n" +
	"\x06result\x18\x04 \x03(\v2).xyz.MarketServer.ExchangeSymbolKlineItemR\x06result*I\n" +
	"\x0eKlineTimeframe\x12\x1f\n" +
	"\x1bKLINE_TIMEFRAME_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12KLINE_TIMEFRAME_1M\x10\x012t\n" +
	"\x0eMarketServices\x12b\n" +
	"\x0fgetSupportAsset\x12%.xyz.MarketServer.SupportAssetRequest\x1a&.xyz.MarketServer.SupportAssetResponse\"\x002\xdf\x02\n" +
	"\x13MarketSymbolService\x12n\n" +
	"\x11listMarketSymbols\x12*.xyz.MarketServer.ListMarketSymbolsRequest\x1a+.xyz.MarketServer.ListMarketSymbolsResponse\"\x00\x12n\n" +
	"\x11listSymbolMarkets\x12*.xyz.MarketServer.ListSymbolMarketsRequest\x1a+.xyz.MarketServer.ListSymbolMarketsResponse\"\x00\x12h\n" +
	"\x0fgetSymbolMarket\x12(.xyz.MarketServer.GetSymbolMarketRequest\x1a).xyz.MarketServer.GetSymbolMarketResponse\"\x002\x8b\x03\n" +
	"\x13FiatCurrencyService\x12e\n" +
	"\x0elistCurrencies\x12'.xyz.MarketServer.ListCurrenciesRequest\x1a(.xyz.MarketServer.ListCurrenciesResponse\"\x00\x12\x89\x01\n" +
	"\x1alistSymbolMarketCurrencies\x123.xyz.MarketServer.ListSymbolMarketCurrenciesRequest\x1a4.xyz.MarketServer.ListSymbolMarketCurrenciesResponse\"\x00\x12\x80\x01\n" +
	"\x17getSymbolMarketCurrency\x120.xyz.MarketServer.GetSymbolMarketCurrencyRequest\x1a1.xyz.MarketServer.GetSymbolMarketCurrencyResponse\"\x002\xdc\x01\n" +
	"\fKlineService\x12Y\n" +
	"\n" +
	"listKlines\x12#.xyz.MarketServer.ListKlinesRequest\x1a$.xyz.MarketServer.ListKlinesResponse\"\x00\x12q\n" +
	"\x12listExchangeKlines\x12+.xyz.MarketServer.ListExchangeKlinesRequest\x1a,.xyz.MarketServer.ListExchangeKlinesResponse\"\x00B)\n" +
	"\x10xyz.MarketServerZ\x15./services/grpc/protob\x06proto3"

var (
	file_market_services_proto_rawDescOnce sync.Once
	file_market_services_proto_rawDescData []byte
)

func file_market_services_proto_rawDescGZIP() []byte {
	file_market_services_proto_rawDescOnce.Do(func() {
		file_market_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_services_proto_rawDesc), len(file_market_services_proto_rawDesc)))
	})
	return file_market_services_proto_rawDescData
}

var file_market_services_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_market_services_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_market_services_proto_goTypes = []any{
	(KlineTimeframe)(0),                        // 0: xyz.MarketServer.KlineTimeframe
	(*PaginationRequest)(nil),                  // 1: xyz.MarketServer.PaginationRequest
	(*PaginationResponse)(nil),                 // 2: xyz.MarketServer.PaginationResponse
	(*AssetItem)(nil),                          // 3: xyz.MarketServer.AssetItem
	(*SupportAssetRequest)(nil),                // 4: xyz.MarketServer.SupportAssetRequest
	(*SupportAssetResponse)(nil),               // 5: xyz.MarketServer.SupportAssetResponse
	(*MarketSymbolItem)(nil),                   // 6: xyz.MarketServer.MarketSymbolItem
	(*ListMarketSymbolsRequest)(nil),           // 7: xyz.MarketServer.ListMarketSymbolsRequest
	(*ListMarketSymbolsResponse)(nil),          // 8: xyz.MarketServer.ListMarketSymbolsResponse
	(*SymbolMarketItem)(nil),                   // 9: xyz.MarketServer.SymbolMarketItem
	(*ListSymbolMarketsRequest)(nil),           // 10: xyz.MarketServer.ListSymbolMarketsRequest
	(*ListSymbolMarketsResponse)(nil),          // 11: xyz.MarketServer.ListSymbolMarketsResponse
	(*GetSymbolMarketRequest)(nil),             // 12: xyz.MarketServer.GetSymbolMarketRequest
	(*GetSymbolMarketResponse)(nil),            // 13: xyz.MarketServer.GetSymbolMarketResponse
	(*CurrencyItem)(nil),                       // 14: xyz.MarketServer.CurrencyItem
	(*ListCurrenciesRequest)(nil),              // 15: xyz.MarketServer.ListCurrenciesRequest
	(*ListCurrenciesResponse)(nil),             // 16: xyz.MarketServer.ListCurrenciesResponse
	(*SymbolMarketCurrencyItem)(nil),           // 17: xyz.MarketServer.SymbolMarketCurrencyItem
	(*ListSymbolMarketCurrenciesRequest)(nil),  // 18: xyz.MarketServer.ListSymbolMarketCurrenciesRequest
	(*ListSymbolMarketCurrenciesResponse)(nil), // 19: xyz.MarketServer.ListSymbolMarketCurrenciesResponse
	(*GetSymbolMarketCurrencyRequest)(nil),     // 20: xyz.MarketServer.GetSymbolMarketCurrencyRequest
	(*GetSymbolMarketCurrencyResponse)(nil),    // 21: xyz.MarketServer.GetSymbolMarketCurrencyResponse
	(*SymbolKlineItem)(nil),                    // 22: xyz.MarketServer.SymbolKlineItem
	(*ListKlinesRequest)(nil),                  // 23: xyz.MarketServer.ListKlinesRequest
	(*ListKlinesResponse)(nil),                 // 24: xyz.MarketServer.ListKlinesResponse
	(*ExchangeSymbolKlineItem)(nil),            // 25: xyz.MarketServer.ExchangeSymbolKlineItem
	(*ListExchangeKlinesRequest)(nil),          // 26: xyz.MarketServer.ListExchangeKlinesRequest
	(*ListExchangeKlinesResponse)(nil),         // 27: xyz.MarketServer.ListExchangeKlinesResponse
}
var file_market_services_proto_depIdxs = []int32{
	3,  // 0: xyz.MarketServer.SupportAssetResponse.asset:type_name -> xyz.MarketServer.AssetItem
	1,  // 1: xyz.MarketServer.ListMarketSymbolsRequest.pagination:type_name -> xyz.MarketServer.PaginationRequest
	2,  // 2: xyz.MarketServer.ListMarketSymbolsResponse.pagination:type_name -> xyz.MarketServer.PaginationResponse
	6,  // 3: xyz.MarketServer.ListMarketSymbolsResponse.result:type_name -> xyz.MarketServer.MarketSymbolItem
	1,  // 4: xyz.MarketServer.ListSymbolMarketsRequest.pagination:type_name -> xyz.MarketServer.PaginationRequest
	2,  // 5: xyz.MarketServer.ListSymbolMarketsResponse.pagination:type_name -> xyz.MarketServer.PaginationResponse
	9,  // 6: xyz.MarketServer.ListSymbolMarketsResponse.result:type_name -> xyz.MarketServer.SymbolMarketItem
	9,  // 7: xyz.MarketServer.GetSymbolMarketResponse.result:type_name -> xyz.MarketServer.SymbolMarketItem
	1,  // 8: xyz.MarketServer.ListCurrenciesRequest.pagination:type_name -> xyz.MarketServer.PaginationRequest
	2,  // 9: xyz.MarketServer.ListCurrenciesResponse.pagination:type_name -> xyz.MarketServer.PaginationResponse
	14, // 10: xyz.MarketServer.ListCurrenciesResponse.result:type_name -> xyz.MarketServer.CurrencyItem
	1,  // 11: xyz.MarketServer.ListSymbolMarketCurrenciesRequest.pagination:type_name -> xyz.MarketServer.PaginationRequest
	2,  // 12: xyz.MarketServer.ListSymbolMarketCurrenciesResponse.pagination:type_name -> xyz.MarketServer.PaginationResponse
	17, // 13: xyz.MarketServer.ListSymbolMarketCurrenciesResponse.result:type_name -> xyz.MarketServer.SymbolMarketCurrencyItem
	17, // 14: xyz.MarketServer.GetSymbolMarketCurrencyResponse.result:type_name -> xyz.MarketServer.SymbolMarketCurrencyItem
	0,  // 15: xyz.MarketServer.SymbolKlineItem.timeframe:type_name -> xyz.MarketServer.KlineTimeframe
	0,  // 16: xyz.MarketServer.ListKlinesRequest.timeframe:type_name -> xyz.MarketServer.KlineTimeframe
	1,  // 17: xyz.MarketServer.ListKlinesRequest.pagination:type_name -> xyz.MarketServer.PaginationRequest
	2,  // 18: xyz.MarketServer.ListKlinesResponse.pagination:type_name -> xyz.MarketServer.PaginationResponse
	22, // 19: xyz.MarketServer.ListKlinesResponse.result:type_name -> xyz.MarketServer.SymbolKlineItem
	0,  // 20: xyz.MarketServer.ExchangeSymbolKlineItem.timeframe:type_name -> xyz.MarketServer.KlineTimeframe
	0,  // 21: xyz.MarketServer.ListExchangeKlinesRequest.timeframe:type_name -> xyz.MarketServer.KlineTimeframe
	1,  // 22: xyz.MarketServer.ListExchangeKlinesRequest.pagination:type_name -> xyz.MarketServer.PaginationRequest
	2,  // 23: xyz.MarketServer.ListExchangeKlinesResponse.pagination:type_name -> xyz.MarketServer.PaginationResponse
	25, // 24: xyz.MarketServer.ListExchangeKlinesResponse.result:type_name -> xyz.MarketServer.ExchangeSymbolKlineItem
	4,  // 25: xyz.MarketServer.MarketServices.getSupportAsset:input_type -> xyz.MarketServer.SupportAssetRequest
	7,  // 26: xyz.MarketServer.MarketSymbolService.listMarketSymbols:input_type -> xyz.MarketServer.ListMarketSymbolsRequest
	10, // 27: xyz.MarketServer.MarketSymbolService.listSymbolMarkets:input_type -> xyz.MarketServer.ListSymbolMarketsRequest
	12, // 28: xyz.MarketServer.MarketSymbolService.getSymbolMarket:input_type -> xyz.MarketServer.GetSymbolMarketRequest
	15, // 29: xyz.MarketServer.FiatCurrencyService.listCurrencies:input_type -> xyz.MarketServer.ListCurrenciesRequest
	18, // 30: xyz.MarketServer.FiatCurrencyService.listSymbolMarketCurrencies:input_type -> xyz.MarketServer.ListSymbolMarketCurrenciesRequest
	20, // 31: xyz.MarketServer.FiatCurrencyService.getSymbolMarketCurrency:input_type -> xyz.MarketServer.GetSymbolMarketCurrencyRequest
	23, // 32: xyz.MarketServer.KlineService.listKlines:input_type -> xyz.MarketServer.ListKlinesRequest
	26, // 33: xyz.MarketServer.KlineService.listExchangeKlines:input_type -> xyz.MarketServer.ListExchangeKlinesRequest
	5,  // 34: xyz.MarketServer.MarketServices.getSupportAsset:output_type -> xyz.MarketServer.SupportAssetResponse
	8,  // 35: xyz.MarketServer.MarketSymbolService.listMarketSymbols:output_type -> xyz.MarketServer.ListMarketSymbolsResponse
	11, // 36: xyz.MarketServer.MarketSymbolService.listSymbolMarkets:output_type -> xyz.MarketServer.ListSymbolMarketsResponse
	13, // 37: xyz.MarketServer.MarketSymbolService.getSymbolMarket:output_type -> xyz.MarketServer.GetSymbolMarketResponse
	16, // 38: xyz.MarketServer.FiatCurrencyService.listCurrencies:output_type -> xyz.MarketServer.ListCurrenciesResponse
	19, // 39: xyz.MarketServer.FiatCurrencyService.listSymbolMarketCurrencies:output_type -> xyz.MarketServer.ListSymbolMarketCurrenciesResponse
	21, // 40: xyz.MarketServer.FiatCurrencyService.getSymbolMarketCurrency:output_type -> xyz.MarketServer.GetSymbolMarketCurrencyResponse
	24, // 41: xyz.MarketServer.KlineService.listKlines:output_type -> xyz.MarketServer.ListKlinesResponse
	27, // 42: xyz.MarketServer.KlineService.listExchangeKlines:output_type -> xyz.MarketServer.ListExchangeKlinesResponse
	34, // [34:43] is the sub-list for method output_type
	25, // [25:34] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_market_services_proto_init() }
func file_market_services_proto_init() {
	if File_market_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_services_proto_rawDesc), len(file_market_services_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_market_services_proto_goTypes,
		DependencyIndexes: file_market_services_proto_depIdxs,
		EnumInfos:         file_market_services_proto_enumTypes,
		MessageInfos:      file_market_services_proto_msgTypes,
	}.Build()
	File_market_services_proto = out.File
	file_market_services_proto_goTypes = nil
	file_market_services_proto_depIdxs = nil
}
