// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: market_services.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	AssetName     string                 `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	AssetSymbol   string                 `protobuf:"bytes,3,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	AssetLogo     string                 `protobuf:"bytes,4,opt,name=asset_logo,json=assetLogo,proto3" json:"asset_logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetItem) Reset() {
	*x = AssetItem{}
	mi := &file_market_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetItem) ProtoMessage() {}

func (x *AssetItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetItem.ProtoReflect.Descriptor instead.
func (*AssetItem) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{0}
}

func (x *AssetItem) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *AssetItem) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *AssetItem) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *AssetItem) GetAssetLogo() string {
	if x != nil {
		return x.AssetLogo
	}
	return ""
}

type SupportAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportAssetRequest) Reset() {
	*x = SupportAssetRequest{}
	mi := &file_market_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportAssetRequest) ProtoMessage() {}

func (x *SupportAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportAssetRequest.ProtoReflect.Descriptor instead.
func (*SupportAssetRequest) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{1}
}

func (x *SupportAssetRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

type SupportAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Asset         []*AssetItem           `protobuf:"bytes,3,rep,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportAssetResponse) Reset() {
	*x = SupportAssetResponse{}
	mi := &file_market_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportAssetResponse) ProtoMessage() {}

func (x *SupportAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportAssetResponse.ProtoReflect.Descriptor instead.
func (*SupportAssetResponse) Descriptor() ([]byte, []int) {
	return file_market_services_proto_rawDescGZIP(), []int{2}
}

func (x *SupportAssetResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *SupportAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SupportAssetResponse) GetAsset() []*AssetItem {
	if x != nil {
		return x.Asset
	}
	return nil
}

var File_market_services_proto protoreflect.FileDescriptor

const file_market_services_proto_rawDesc = "" +
	"\n" +
	"\x15market_services.proto\x12\x10xyz.MarketServer\"\x80\x01\n" +
	"\tAssetItem\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12!\n" +
	"\fasset_symbol\x18\x03 \x01(\tR\vassetSymbol\x12\x1d\n" +
	"\n" +
	"asset_logo\x18\x04 \x01(\tR\tassetLogo\"<\n" +
	"\x13SupportAssetRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\"\x84\x01\n" +
	"\x14SupportAssetResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x05asset\x18\x03 \x03(\v2\x1b.xyz.MarketServer.AssetItemR\x05asset2t\n" +
	"\x0eMarketServices\x12b\n" +
	"\x0fgetSupportAsset\x12%.xyz.MarketServer.SupportAssetRequest\x1a&.xyz.MarketServer.SupportAssetResponse\"\x00B)\n" +
	"\x10xyz.MarketServerZ\x15./services/grpc/protob\x06proto3"

var (
	file_market_services_proto_rawDescOnce sync.Once
	file_market_services_proto_rawDescData []byte
)

func file_market_services_proto_rawDescGZIP() []byte {
	file_market_services_proto_rawDescOnce.Do(func() {
		file_market_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_services_proto_rawDesc), len(file_market_services_proto_rawDesc)))
	})
	return file_market_services_proto_rawDescData
}

var file_market_services_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_market_services_proto_goTypes = []any{
	(*AssetItem)(nil),            // 0: xyz.MarketServer.AssetItem
	(*SupportAssetRequest)(nil),  // 1: xyz.MarketServer.SupportAssetRequest
	(*SupportAssetResponse)(nil), // 2: xyz.MarketServer.SupportAssetResponse
}
var file_market_services_proto_depIdxs = []int32{
	0, // 0: xyz.MarketServer.SupportAssetResponse.asset:type_name -> xyz.MarketServer.AssetItem
	1, // 1: xyz.MarketServer.MarketServices.getSupportAsset:input_type -> xyz.MarketServer.SupportAssetRequest
	2, // 2: xyz.MarketServer.MarketServices.getSupportAsset:output_type -> xyz.MarketServer.SupportAssetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_services_proto_init() }
func file_market_services_proto_init() {
	if File_market_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_services_proto_rawDesc), len(file_market_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_services_proto_goTypes,
		DependencyIndexes: file_market_services_proto_depIdxs,
		MessageInfos:      file_market_services_proto_msgTypes,
	}.Build()
	File_market_services_proto = out.File
	file_market_services_proto_goTypes = nil
	file_market_services_proto_depIdxs = nil
}
