// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: market_services.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketServices_GetSupportAsset_FullMethodName = "/xyz.MarketServer.MarketServices/getSupportAsset"
)

// MarketServicesClient is the client API for MarketServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServicesClient interface {
	GetSupportAsset(ctx context.Context, in *SupportAssetRequest, opts ...grpc.CallOption) (*SupportAssetResponse, error)
}

type marketServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServicesClient(cc grpc.ClientConnInterface) MarketServicesClient {
	return &marketServicesClient{cc}
}

func (c *marketServicesClient) GetSupportAsset(ctx context.Context, in *SupportAssetRequest, opts ...grpc.CallOption) (*SupportAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupportAssetResponse)
	err := c.cc.Invoke(ctx, MarketServices_GetSupportAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServicesServer is the server API for MarketServices service.
// All implementations should embed UnimplementedMarketServicesServer
// for forward compatibility.
type MarketServicesServer interface {
	GetSupportAsset(context.Context, *SupportAssetRequest) (*SupportAssetResponse, error)
}

// UnimplementedMarketServicesServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServicesServer struct{}

func (UnimplementedMarketServicesServer) GetSupportAsset(context.Context, *SupportAssetRequest) (*SupportAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportAsset not implemented")
}
func (UnimplementedMarketServicesServer) testEmbeddedByValue() {}

// UnsafeMarketServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServicesServer will
// result in compilation errors.
type UnsafeMarketServicesServer interface {
	mustEmbedUnimplementedMarketServicesServer()
}

func RegisterMarketServicesServer(s grpc.ServiceRegistrar, srv MarketServicesServer) {
	// If the following call panics, it indicates UnimplementedMarketServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketServices_ServiceDesc, srv)
}

func _MarketServices_GetSupportAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServicesServer).GetSupportAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketServices_GetSupportAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServicesServer).GetSupportAsset(ctx, req.(*SupportAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketServices_ServiceDesc is the grpc.ServiceDesc for MarketServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.MarketServer.MarketServices",
	HandlerType: (*MarketServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSupportAsset",
			Handler:    _MarketServices_GetSupportAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market_services.proto",
}

const (
	MarketSymbolService_ListMarketSymbols_FullMethodName = "/xyz.MarketServer.MarketSymbolService/listMarketSymbols"
	MarketSymbolService_ListSymbolMarkets_FullMethodName = "/xyz.MarketServer.MarketSymbolService/listSymbolMarkets"
	MarketSymbolService_GetSymbolMarket_FullMethodName   = "/xyz.MarketServer.MarketSymbolService/getSymbolMarket"
)

// MarketSymbolServiceClient is the client API for MarketSymbolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketSymbolServiceClient interface {
	ListMarketSymbols(ctx context.Context, in *ListMarketSymbolsRequest, opts ...grpc.CallOption) (*ListMarketSymbolsResponse, error)
	ListSymbolMarkets(ctx context.Context, in *ListSymbolMarketsRequest, opts ...grpc.CallOption) (*ListSymbolMarketsResponse, error)
	GetSymbolMarket(ctx context.Context, in *GetSymbolMarketRequest, opts ...grpc.CallOption) (*GetSymbolMarketResponse, error)
}

type marketSymbolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketSymbolServiceClient(cc grpc.ClientConnInterface) MarketSymbolServiceClient {
	return &marketSymbolServiceClient{cc}
}

func (c *marketSymbolServiceClient) ListMarketSymbols(ctx context.Context, in *ListMarketSymbolsRequest, opts ...grpc.CallOption) (*ListMarketSymbolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMarketSymbolsResponse)
	err := c.cc.Invoke(ctx, MarketSymbolService_ListMarketSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSymbolServiceClient) ListSymbolMarkets(ctx context.Context, in *ListSymbolMarketsRequest, opts ...grpc.CallOption) (*ListSymbolMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSymbolMarketsResponse)
	err := c.cc.Invoke(ctx, MarketSymbolService_ListSymbolMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSymbolServiceClient) GetSymbolMarket(ctx context.Context, in *GetSymbolMarketRequest, opts ...grpc.CallOption) (*GetSymbolMarketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSymbolMarketResponse)
	err := c.cc.Invoke(ctx, MarketSymbolService_GetSymbolMarket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketSymbolServiceServer is the server API for MarketSymbolService service.
// All implementations should embed UnimplementedMarketSymbolServiceServer
// for forward compatibility.
type MarketSymbolServiceServer interface {
	ListMarketSymbols(context.Context, *ListMarketSymbolsRequest) (*ListMarketSymbolsResponse, error)
	ListSymbolMarkets(context.Context, *ListSymbolMarketsRequest) (*ListSymbolMarketsResponse, error)
	GetSymbolMarket(context.Context, *GetSymbolMarketRequest) (*GetSymbolMarketResponse, error)
}

// UnimplementedMarketSymbolServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketSymbolServiceServer struct{}

func (UnimplementedMarketSymbolServiceServer) ListMarketSymbols(context.Context, *ListMarketSymbolsRequest) (*ListMarketSymbolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMarketSymbols not implemented")
}
func (UnimplementedMarketSymbolServiceServer) ListSymbolMarkets(context.Context, *ListSymbolMarketsRequest) (*ListSymbolMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSymbolMarkets not implemented")
}
func (UnimplementedMarketSymbolServiceServer) GetSymbolMarket(context.Context, *GetSymbolMarketRequest) (*GetSymbolMarketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSymbolMarket not implemented")
}
func (UnimplementedMarketSymbolServiceServer) testEmbeddedByValue() {}

// UnsafeMarketSymbolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketSymbolServiceServer will
// result in compilation errors.
type UnsafeMarketSymbolServiceServer interface {
	mustEmbedUnimplementedMarketSymbolServiceServer()
}

func RegisterMarketSymbolServiceServer(s grpc.ServiceRegistrar, srv MarketSymbolServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketSymbolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketSymbolService_ServiceDesc, srv)
}

func _MarketSymbolService_ListMarketSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMarketSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSymbolServiceServer).ListMarketSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketSymbolService_ListMarketSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSymbolServiceServer).ListMarketSymbols(ctx, req.(*ListMarketSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSymbolService_ListSymbolMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSymbolMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSymbolServiceServer).ListSymbolMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketSymbolService_ListSymbolMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSymbolServiceServer).ListSymbolMarkets(ctx, req.(*ListSymbolMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSymbolService_GetSymbolMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSymbolMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSymbolServiceServer).GetSymbolMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketSymbolService_GetSymbolMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSymbolServiceServer).GetSymbolMarket(ctx, req.(*GetSymbolMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketSymbolService_ServiceDesc is the grpc.ServiceDesc for MarketSymbolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketSymbolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.MarketServer.MarketSymbolService",
	HandlerType: (*MarketSymbolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listMarketSymbols",
			Handler:    _MarketSymbolService_ListMarketSymbols_Handler,
		},
		{
			MethodName: "listSymbolMarkets",
			Handler:    _MarketSymbolService_ListSymbolMarkets_Handler,
		},
		{
			MethodName: "getSymbolMarket",
			Handler:    _MarketSymbolService_GetSymbolMarket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market_services.proto",
}

const (
	FiatCurrencyService_ListCurrencies_FullMethodName             = "/xyz.MarketServer.FiatCurrencyService/listCurrencies"
	FiatCurrencyService_ListSymbolMarketCurrencies_FullMethodName = "/xyz.MarketServer.FiatCurrencyService/listSymbolMarketCurrencies"
	FiatCurrencyService_GetSymbolMarketCurrency_FullMethodName    = "/xyz.MarketServer.FiatCurrencyService/getSymbolMarketCurrency"
)

// FiatCurrencyServiceClient is the client API for FiatCurrencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FiatCurrencyServiceClient interface {
	ListCurrencies(ctx context.Context, in *ListCurrenciesRequest, opts ...grpc.CallOption) (*ListCurrenciesResponse, error)
	// 查询交易对按法币换算后的行情，支持按symbol_guid、currency_guid 过滤
	ListSymbolMarketCurrencies(ctx context.Context, in *ListSymbolMarketCurrenciesRequest, opts ...grpc.CallOption) (*ListSymbolMarketCurrenciesResponse, error)
	// 查询单个交易对在指定法币下的最新行情
	GetSymbolMarketCurrency(ctx context.Context, in *GetSymbolMarketCurrencyRequest, opts ...grpc.CallOption) (*GetSymbolMarketCurrencyResponse, error)
}

type fiatCurrencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFiatCurrencyServiceClient(cc grpc.ClientConnInterface) FiatCurrencyServiceClient {
	return &fiatCurrencyServiceClient{cc}
}

func (c *fiatCurrencyServiceClient) ListCurrencies(ctx context.Context, in *ListCurrenciesRequest, opts ...grpc.CallOption) (*ListCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCurrenciesResponse)
	err := c.cc.Invoke(ctx, FiatCurrencyService_ListCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fiatCurrencyServiceClient) ListSymbolMarketCurrencies(ctx context.Context, in *ListSymbolMarketCurrenciesRequest, opts ...grpc.CallOption) (*ListSymbolMarketCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSymbolMarketCurrenciesResponse)
	err := c.cc.Invoke(ctx, FiatCurrencyService_ListSymbolMarketCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fiatCurrencyServiceClient) GetSymbolMarketCurrency(ctx context.Context, in *GetSymbolMarketCurrencyRequest, opts ...grpc.CallOption) (*GetSymbolMarketCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSymbolMarketCurrencyResponse)
	err := c.cc.Invoke(ctx, FiatCurrencyService_GetSymbolMarketCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FiatCurrencyServiceServer is the server API for FiatCurrencyService service.
// All implementations should embed UnimplementedFiatCurrencyServiceServer
// for forward compatibility.
type FiatCurrencyServiceServer interface {
	ListCurrencies(context.Context, *ListCurrenciesRequest) (*ListCurrenciesResponse, error)
	// 查询交易对按法币换算后的行情，支持按symbol_guid、currency_guid 过滤
	ListSymbolMarketCurrencies(context.Context, *ListSymbolMarketCurrenciesRequest) (*ListSymbolMarketCurrenciesResponse, error)
	// 查询单个交易对在指定法币下的最新行情
	GetSymbolMarketCurrency(context.Context, *GetSymbolMarketCurrencyRequest) (*GetSymbolMarketCurrencyResponse, error)
}

// UnimplementedFiatCurrencyServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFiatCurrencyServiceServer struct{}

func (UnimplementedFiatCurrencyServiceServer) ListCurrencies(context.Context, *ListCurrenciesRequest) (*ListCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCurrencies not implemented")
}
func (UnimplementedFiatCurrencyServiceServer) ListSymbolMarketCurrencies(context.Context, *ListSymbolMarketCurrenciesRequest) (*ListSymbolMarketCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSymbolMarketCurrencies not implemented")
}
func (UnimplementedFiatCurrencyServiceServer) GetSymbolMarketCurrency(context.Context, *GetSymbolMarketCurrencyRequest) (*GetSymbolMarketCurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSymbolMarketCurrency not implemented")
}
func (UnimplementedFiatCurrencyServiceServer) testEmbeddedByValue() {}

// UnsafeFiatCurrencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FiatCurrencyServiceServer will
// result in compilation errors.
type UnsafeFiatCurrencyServiceServer interface {
	mustEmbedUnimplementedFiatCurrencyServiceServer()
}

func RegisterFiatCurrencyServiceServer(s grpc.ServiceRegistrar, srv FiatCurrencyServiceServer) {
	// If the following call panics, it indicates UnimplementedFiatCurrencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FiatCurrencyService_ServiceDesc, srv)
}

func _FiatCurrencyService_ListCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiatCurrencyServiceServer).ListCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiatCurrencyService_ListCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiatCurrencyServiceServer).ListCurrencies(ctx, req.(*ListCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FiatCurrencyService_ListSymbolMarketCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSymbolMarketCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiatCurrencyServiceServer).ListSymbolMarketCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiatCurrencyService_ListSymbolMarketCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiatCurrencyServiceServer).ListSymbolMarketCurrencies(ctx, req.(*ListSymbolMarketCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FiatCurrencyService_GetSymbolMarketCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSymbolMarketCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiatCurrencyServiceServer).GetSymbolMarketCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiatCurrencyService_GetSymbolMarketCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiatCurrencyServiceServer).GetSymbolMarketCurrency(ctx, req.(*GetSymbolMarketCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FiatCurrencyService_ServiceDesc is the grpc.ServiceDesc for FiatCurrencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FiatCurrencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.MarketServer.FiatCurrencyService",
	HandlerType: (*FiatCurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listCurrencies",
			Handler:    _FiatCurrencyService_ListCurrencies_Handler,
		},
		{
			MethodName: "listSymbolMarketCurrencies",
			Handler:    _FiatCurrencyService_ListSymbolMarketCurrencies_Handler,
		},
		{
			MethodName: "getSymbolMarketCurrency",
			Handler:    _FiatCurrencyService_GetSymbolMarketCurrency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market_services.proto",
}

const (
	KlineService_ListKlines_FullMethodName         = "/xyz.MarketServer.KlineService/listKlines"
	KlineService_ListExchangeKlines_FullMethodName = "/xyz.MarketServer.KlineService/listExchangeKlines"
)

// KlineServiceClient is the client API for KlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KlineServiceClient interface {
	// 查询聚合 K 线，必传 symbol_guid，支持 start_timestamp、end_timestamp、pagination
	ListKlines(ctx context.Context, in *ListKlinesRequest, opts ...grpc.CallOption) (*ListKlinesResponse, error)
	// 查询交易所维度 K 线，必传 symbol_guid，可选 exchange_guid
	ListExchangeKlines(ctx context.Context, in *ListExchangeKlinesRequest, opts ...grpc.CallOption) (*ListExchangeKlinesResponse, error)
}

type klineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKlineServiceClient(cc grpc.ClientConnInterface) KlineServiceClient {
	return &klineServiceClient{cc}
}

func (c *klineServiceClient) ListKlines(ctx context.Context, in *ListKlinesRequest, opts ...grpc.CallOption) (*ListKlinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKlinesResponse)
	err := c.cc.Invoke(ctx, KlineService_ListKlines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *klineServiceClient) ListExchangeKlines(ctx context.Context, in *ListExchangeKlinesRequest, opts ...grpc.CallOption) (*ListExchangeKlinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExchangeKlinesResponse)
	err := c.cc.Invoke(ctx, KlineService_ListExchangeKlines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KlineServiceServer is the server API for KlineService service.
// All implementations should embed UnimplementedKlineServiceServer
// for forward compatibility.
type KlineServiceServer interface {
	// 查询聚合 K 线，必传 symbol_guid，支持 start_timestamp、end_timestamp、pagination
	ListKlines(context.Context, *ListKlinesRequest) (*ListKlinesResponse, error)
	// 查询交易所维度 K 线，必传 symbol_guid，可选 exchange_guid
	ListExchangeKlines(context.Context, *ListExchangeKlinesRequest) (*ListExchangeKlinesResponse, error)
}

// UnimplementedKlineServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKlineServiceServer struct{}

func (UnimplementedKlineServiceServer) ListKlines(context.Context, *ListKlinesRequest) (*ListKlinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKlines not implemented")
}
func (UnimplementedKlineServiceServer) ListExchangeKlines(context.Context, *ListExchangeKlinesRequest) (*ListExchangeKlinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExchangeKlines not implemented")
}
func (UnimplementedKlineServiceServer) testEmbeddedByValue() {}

// UnsafeKlineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KlineServiceServer will
// result in compilation errors.
type UnsafeKlineServiceServer interface {
	mustEmbedUnimplementedKlineServiceServer()
}

func RegisterKlineServiceServer(s grpc.ServiceRegistrar, srv KlineServiceServer) {
	// If the following call panics, it indicates UnimplementedKlineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KlineService_ServiceDesc, srv)
}

func _KlineService_ListKlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKlinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KlineServiceServer).ListKlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KlineService_ListKlines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KlineServiceServer).ListKlines(ctx, req.(*ListKlinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KlineService_ListExchangeKlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExchangeKlinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KlineServiceServer).ListExchangeKlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KlineService_ListExchangeKlines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KlineServiceServer).ListExchangeKlines(ctx, req.(*ListExchangeKlinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KlineService_ServiceDesc is the grpc.ServiceDesc for KlineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KlineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.MarketServer.KlineService",
	HandlerType: (*KlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listKlines",
			Handler:    _KlineService_ListKlines_Handler,
		},
		{
			MethodName: "listExchangeKlines",
			Handler:    _KlineService_ListExchangeKlines_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market_services.proto",
}
